<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GoogleAuth.proto

namespace App\Protobuf\GoogleAuth;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>app.Protobuf.GoogleAuth.Payload</code>
 */
class Payload extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .app.Protobuf.GoogleAuth.Payload.OtpParameters otp_parameters = 1;</code>
     */
    private $otp_parameters;
    /**
     * Generated from protobuf field <code>int32 version = 2;</code>
     */
    protected $version = 0;
    /**
     * Generated from protobuf field <code>int32 batch_size = 3;</code>
     */
    protected $batch_size = 0;
    /**
     * Generated from protobuf field <code>int32 batch_index = 4;</code>
     */
    protected $batch_index = 0;
    /**
     * Generated from protobuf field <code>int32 batch_id = 5;</code>
     */
    protected $batch_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Protobuf\GoogleAuth\Payload\OtpParameters[]|\Google\Protobuf\Internal\RepeatedField $otp_parameters
     *     @type int $version
     *     @type int $batch_size
     *     @type int $batch_index
     *     @type int $batch_id
     * }
     */
    public function __construct($data = NULL) {
        \App\Protobuf\GPBMetadata\GoogleAuth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .app.Protobuf.GoogleAuth.Payload.OtpParameters otp_parameters = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOtpParameters()
    {
        return $this->otp_parameters;
    }

    /**
     * Generated from protobuf field <code>repeated .app.Protobuf.GoogleAuth.Payload.OtpParameters otp_parameters = 1;</code>
     * @param \App\Protobuf\GoogleAuth\Payload\OtpParameters[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOtpParameters($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Protobuf\GoogleAuth\Payload\OtpParameters::class);
        $this->otp_parameters = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 version = 2;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>int32 version = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 batch_size = 3;</code>
     * @return int
     */
    public function getBatchSize()
    {
        return $this->batch_size;
    }

    /**
     * Generated from protobuf field <code>int32 batch_size = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setBatchSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->batch_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 batch_index = 4;</code>
     * @return int
     */
    public function getBatchIndex()
    {
        return $this->batch_index;
    }

    /**
     * Generated from protobuf field <code>int32 batch_index = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setBatchIndex($var)
    {
        GPBUtil::checkInt32($var);
        $this->batch_index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 batch_id = 5;</code>
     * @return int
     */
    public function getBatchId()
    {
        return $this->batch_id;
    }

    /**
     * Generated from protobuf field <code>int32 batch_id = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setBatchId($var)
    {
        GPBUtil::checkInt32($var);
        $this->batch_id = $var;

        return $this;
    }

}

