<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GoogleAuth.proto

namespace App\Protobuf\GoogleAuth;

if (false) {
    /**
     * This class is deprecated. Use App\Protobuf\GoogleAuth\Payload\DigitCount instead.
     * @deprecated
     */
    class Payload_DigitCount {}
}
class_exists(Payload\DigitCount::class);
@trigger_error('App\Protobuf\GoogleAuth\Payload_DigitCount is deprecated and will be removed in the next major release. Use App\Protobuf\GoogleAuth\Payload\DigitCount instead', E_USER_DEPRECATED);

