<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GoogleAuth.proto

namespace App\Protobuf\GoogleAuth;

if (false) {
    /**
     * This class is deprecated. Use App\Protobuf\GoogleAuth\Payload\OtpParameters instead.
     * @deprecated
     */
    class Payload_OtpParameters {}
}
class_exists(Payload\OtpParameters::class);
@trigger_error('App\Protobuf\GoogleAuth\Payload_OtpParameters is deprecated and will be removed in the next major release. Use App\Protobuf\GoogleAuth\Payload\OtpParameters instead', E_USER_DEPRECATED);

