<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GoogleAuth.proto

namespace App\Protobuf\GoogleAuth;

if (false) {
    /**
     * This class is deprecated. Use App\Protobuf\GoogleAuth\Payload\OtpType instead.
     * @deprecated
     */
    class Payload_OtpType {}
}
class_exists(Payload\OtpType::class);
@trigger_error('App\Protobuf\GoogleAuth\Payload_OtpType is deprecated and will be removed in the next major release. Use App\Protobuf\GoogleAuth\Payload\OtpType instead', E_USER_DEPRECATED);

