<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GoogleAuth.proto

namespace App\Protobuf\GoogleAuth\Payload;

use UnexpectedValueException;

/**
 * Protobuf type <code>app.Protobuf.GoogleAuth.Payload.DigitCount</code>
 */
class DigitCount
{
    /**
     * Generated from protobuf enum <code>DIGIT_COUNT_UNSPECIFIED = 0;</code>
     */
    const DIGIT_COUNT_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>DIGIT_COUNT_SIX = 1;</code>
     */
    const DIGIT_COUNT_SIX = 1;
    /**
     * Generated from protobuf enum <code>DIGIT_COUNT_EIGHT = 2;</code>
     */
    const DIGIT_COUNT_EIGHT = 2;

    private static $valueToName = [
        self::DIGIT_COUNT_UNSPECIFIED => 'DIGIT_COUNT_UNSPECIFIED',
        self::DIGIT_COUNT_SIX => 'DIGIT_COUNT_SIX',
        self::DIGIT_COUNT_EIGHT => 'DIGIT_COUNT_EIGHT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(DigitCount::class, \App\Protobuf\GoogleAuth\Payload_DigitCount::class);

