<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GoogleAuth.proto

namespace App\Protobuf\GoogleAuth\Payload;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>app.Protobuf.GoogleAuth.Payload.OtpParameters</code>
 */
class OtpParameters extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes secret = 1;</code>
     */
    protected $secret = '';
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string issuer = 3;</code>
     */
    protected $issuer = '';
    /**
     * Generated from protobuf field <code>.app.Protobuf.GoogleAuth.Payload.Algorithm algorithm = 4;</code>
     */
    protected $algorithm = 0;
    /**
     * Generated from protobuf field <code>.app.Protobuf.GoogleAuth.Payload.DigitCount digits = 5;</code>
     */
    protected $digits = 0;
    /**
     * Generated from protobuf field <code>.app.Protobuf.GoogleAuth.Payload.OtpType type = 6;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>int64 counter = 7;</code>
     */
    protected $counter = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $secret
     *     @type string $name
     *     @type string $issuer
     *     @type int $algorithm
     *     @type int $digits
     *     @type int $type
     *     @type int|string $counter
     * }
     */
    public function __construct($data = NULL) {
        \App\Protobuf\GPBMetadata\GoogleAuth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes secret = 1;</code>
     * @return string
     */
    public function getSecret()
    {
        return $this->secret;
    }

    /**
     * Generated from protobuf field <code>bytes secret = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSecret($var)
    {
        GPBUtil::checkString($var, False);
        $this->secret = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string issuer = 3;</code>
     * @return string
     */
    public function getIssuer()
    {
        return $this->issuer;
    }

    /**
     * Generated from protobuf field <code>string issuer = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setIssuer($var)
    {
        GPBUtil::checkString($var, True);
        $this->issuer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.app.Protobuf.GoogleAuth.Payload.Algorithm algorithm = 4;</code>
     * @return int
     */
    public function getAlgorithm()
    {
        return $this->algorithm;
    }

    /**
     * Generated from protobuf field <code>.app.Protobuf.GoogleAuth.Payload.Algorithm algorithm = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setAlgorithm($var)
    {
        GPBUtil::checkEnum($var, \App\Protobuf\GoogleAuth\Payload_Algorithm::class);
        $this->algorithm = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.app.Protobuf.GoogleAuth.Payload.DigitCount digits = 5;</code>
     * @return int
     */
    public function getDigits()
    {
        return $this->digits;
    }

    /**
     * Generated from protobuf field <code>.app.Protobuf.GoogleAuth.Payload.DigitCount digits = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setDigits($var)
    {
        GPBUtil::checkEnum($var, \App\Protobuf\GoogleAuth\Payload_DigitCount::class);
        $this->digits = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.app.Protobuf.GoogleAuth.Payload.OtpType type = 6;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.app.Protobuf.GoogleAuth.Payload.OtpType type = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \App\Protobuf\GoogleAuth\Payload_OtpType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 counter = 7;</code>
     * @return int|string
     */
    public function getCounter()
    {
        return $this->counter;
    }

    /**
     * Generated from protobuf field <code>int64 counter = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCounter($var)
    {
        GPBUtil::checkInt64($var);
        $this->counter = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(OtpParameters::class, \App\Protobuf\GoogleAuth\Payload_OtpParameters::class);

