<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GoogleAuth.proto

namespace App\Protobuf;

use App\Models\TwoFAccount;

class GAuthValueMapping
{
    const ALGORITHM = [
        'ALGORITHM_UNSPECIFIED' => '',
        'ALGORITHM_SHA1' => TwoFAccount::SHA1,
        'ALGORITHM_SHA256' => TwoFAccount::SHA256,
        'ALGORITHM_SHA512' => TwoFAccount::SHA512,
        'ALGORITHM_MD5' => TwoFAccount::MD5
    ];

    const DIGIT_COUNT = [
        'DIGIT_COUNT_UNSPECIFIED' => '',
        'DIGIT_COUNT_SIX' => 6,
        'DIGIT_COUNT_EIGHT' => 8
    ];

    const OTP_TYPE = [
        'OTP_TYPE_UNSPECIFIED' => '',
        'OTP_TYPE_HOTP' => TwoFAccount::HOTP,
        'OTP_TYPE_TOTP' => TwoFAccount::TOTP
    ];

    private function __construct() {}
}