<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GoogleAuth.proto

namespace App\Protobuf;

class GAuthValueMapping
{
    const ALGORITHM = [
        'ALGORITHM_UNSPECIFIED' => '',
        'ALGORITHM_SHA1' => 'sha1',
        'ALGORITHM_SHA256' => 'sha256',
        'ALGORITHM_SHA512' => 'sha512',
        'ALGORITHM_MD5' => 'md5'
    ];

    const DIGIT_COUNT = [
        'DIGIT_COUNT_UNSPECIFIED' => '',
        'DIGIT_COUNT_SIX' => 6,
        'DIGIT_COUNT_EIGHT' => 8
    ];

    const OTP_TYPE = [
        'OTP_TYPE_UNSPECIFIED' => '',
        'OTP_TYPE_HOTP' => 'hotp',
        'OTP_TYPE_TOTP' => 'totp'
    ];

    private function __construct() {}
}